# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InteractiveConeBeamReconstruction_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Interactive_Cone_Beam_Reconstruction(object):
    def setupUi(self, Interactive_Cone_Beam_Reconstruction):
        Interactive_Cone_Beam_Reconstruction.setObjectName("Interactive_Cone_Beam_Reconstruction")
        Interactive_Cone_Beam_Reconstruction.resize(2263, 1080)
        Interactive_Cone_Beam_Reconstruction.setMinimumSize(QtCore.QSize(640, 360))
        self.centralwidget = QtWidgets.QWidget(Interactive_Cone_Beam_Reconstruction)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.config_tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_tabs.sizePolicy().hasHeightForWidth())
        self.config_tabs.setSizePolicy(sizePolicy)
        self.config_tabs.setAutoFillBackground(False)
        self.config_tabs.setStyleSheet("")
        self.config_tabs.setElideMode(QtCore.Qt.ElideMiddle)
        self.config_tabs.setObjectName("config_tabs")
        self.config_tab_simple = QtWidgets.QWidget()
        self.config_tab_simple.setObjectName("config_tab_simple")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.config_tab_simple)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fLayout_sdd_sid_simple = QtWidgets.QFormLayout()
        self.fLayout_sdd_sid_simple.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.fLayout_sdd_sid_simple.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fLayout_sdd_sid_simple.setObjectName("fLayout_sdd_sid_simple")
        self.label_sdd_simple = QtWidgets.QLabel(self.config_tab_simple)
        self.label_sdd_simple.setObjectName("label_sdd_simple")
        self.fLayout_sdd_sid_simple.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sdd_simple)
        self.label_sid_simple = QtWidgets.QLabel(self.config_tab_simple)
        self.label_sid_simple.setObjectName("label_sid_simple")
        self.fLayout_sdd_sid_simple.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sid_simple)
        self.hLayout_sdd_simple = QtWidgets.QHBoxLayout()
        self.hLayout_sdd_simple.setObjectName("hLayout_sdd_simple")
        self.sB_sdd_simple = QtWidgets.QDoubleSpinBox(self.config_tab_simple)
        self.sB_sdd_simple.setMaximum(100000.0)
        self.sB_sdd_simple.setObjectName("sB_sdd_simple")
        self.hLayout_sdd_simple.addWidget(self.sB_sdd_simple)
        self.hS_sdd_simple = QtWidgets.QSlider(self.config_tab_simple)
        self.hS_sdd_simple.setMaximum(2000)
        self.hS_sdd_simple.setOrientation(QtCore.Qt.Horizontal)
        self.hS_sdd_simple.setObjectName("hS_sdd_simple")
        self.hLayout_sdd_simple.addWidget(self.hS_sdd_simple)
        self.fLayout_sdd_sid_simple.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.hLayout_sdd_simple)
        self.hLayout_sid_simple = QtWidgets.QHBoxLayout()
        self.hLayout_sid_simple.setObjectName("hLayout_sid_simple")
        self.sB_sid_simple = QtWidgets.QDoubleSpinBox(self.config_tab_simple)
        self.sB_sid_simple.setMaximum(100000.0)
        self.sB_sid_simple.setObjectName("sB_sid_simple")
        self.hLayout_sid_simple.addWidget(self.sB_sid_simple)
        self.hS_sid_simple = QtWidgets.QSlider(self.config_tab_simple)
        self.hS_sid_simple.setMaximum(1500)
        self.hS_sid_simple.setOrientation(QtCore.Qt.Horizontal)
        self.hS_sid_simple.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.hS_sid_simple.setTickInterval(100)
        self.hS_sid_simple.setObjectName("hS_sid_simple")
        self.hLayout_sid_simple.addWidget(self.hS_sid_simple)
        self.fLayout_sdd_sid_simple.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hLayout_sid_simple)
        self.horizontalLayout_5.addLayout(self.fLayout_sdd_sid_simple)
        self.fLayout_det_size = QtWidgets.QFormLayout()
        self.fLayout_det_size.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.fLayout_det_size.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fLayout_det_size.setObjectName("fLayout_det_size")
        self.label_det_width_simple = QtWidgets.QLabel(self.config_tab_simple)
        self.label_det_width_simple.setObjectName("label_det_width_simple")
        self.fLayout_det_size.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_det_width_simple)
        self.hLayout_det_width_simple = QtWidgets.QHBoxLayout()
        self.hLayout_det_width_simple.setObjectName("hLayout_det_width_simple")
        self.sB_det_width_simple = QtWidgets.QSpinBox(self.config_tab_simple)
        self.sB_det_width_simple.setMaximum(8192)
        self.sB_det_width_simple.setObjectName("sB_det_width_simple")
        self.hLayout_det_width_simple.addWidget(self.sB_det_width_simple)
        self.hS_det_width_simple = QtWidgets.QSlider(self.config_tab_simple)
        self.hS_det_width_simple.setMaximum(2048)
        self.hS_det_width_simple.setOrientation(QtCore.Qt.Horizontal)
        self.hS_det_width_simple.setObjectName("hS_det_width_simple")
        self.hLayout_det_width_simple.addWidget(self.hS_det_width_simple)
        self.fLayout_det_size.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hLayout_det_width_simple)
        self.label_det_height_simple = QtWidgets.QLabel(self.config_tab_simple)
        self.label_det_height_simple.setObjectName("label_det_height_simple")
        self.fLayout_det_size.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_det_height_simple)
        self.hLayout_det_height_simple = QtWidgets.QHBoxLayout()
        self.hLayout_det_height_simple.setObjectName("hLayout_det_height_simple")
        self.sB_det_height_simple = QtWidgets.QSpinBox(self.config_tab_simple)
        self.sB_det_height_simple.setMaximum(8192)
        self.sB_det_height_simple.setObjectName("sB_det_height_simple")
        self.hLayout_det_height_simple.addWidget(self.sB_det_height_simple)
        self.hS_det_height_simple = QtWidgets.QSlider(self.config_tab_simple)
        self.hS_det_height_simple.setMaximum(2048)
        self.hS_det_height_simple.setOrientation(QtCore.Qt.Horizontal)
        self.hS_det_height_simple.setObjectName("hS_det_height_simple")
        self.hLayout_det_height_simple.addWidget(self.hS_det_height_simple)
        self.fLayout_det_size.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.hLayout_det_height_simple)
        self.horizontalLayout_5.addLayout(self.fLayout_det_size)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.config_tabs.addTab(self.config_tab_simple, "")
        self.config_tab_advanced = QtWidgets.QWidget()
        self.config_tab_advanced.setObjectName("config_tab_advanced")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.config_tab_advanced)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gB_trajectory = QtWidgets.QGroupBox(self.config_tab_advanced)
        self.gB_trajectory.setObjectName("gB_trajectory")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gB_trajectory)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fLayout_traj_l = QtWidgets.QFormLayout()
        self.fLayout_traj_l.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.fLayout_traj_l.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fLayout_traj_l.setObjectName("fLayout_traj_l")
        self.label_sdd = QtWidgets.QLabel(self.gB_trajectory)
        self.label_sdd.setObjectName("label_sdd")
        self.fLayout_traj_l.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sdd)
        self.sB_sdd = QtWidgets.QDoubleSpinBox(self.gB_trajectory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_sdd.sizePolicy().hasHeightForWidth())
        self.sB_sdd.setSizePolicy(sizePolicy)
        self.sB_sdd.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.sB_sdd.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sB_sdd.setAccelerated(False)
        self.sB_sdd.setMaximum(100000.0)
        self.sB_sdd.setObjectName("sB_sdd")
        self.fLayout_traj_l.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sB_sdd)
        self.label_sid = QtWidgets.QLabel(self.gB_trajectory)
        self.label_sid.setObjectName("label_sid")
        self.fLayout_traj_l.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sid)
        self.sB_sid = QtWidgets.QDoubleSpinBox(self.gB_trajectory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_sid.sizePolicy().hasHeightForWidth())
        self.sB_sid.setSizePolicy(sizePolicy)
        self.sB_sid.setMaximum(100000.0)
        self.sB_sid.setObjectName("sB_sid")
        self.fLayout_traj_l.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_sid)
        self.label_ang_incr = QtWidgets.QLabel(self.gB_trajectory)
        self.label_ang_incr.setObjectName("label_ang_incr")
        self.fLayout_traj_l.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_ang_incr)
        self.sB_ang_incr = QtWidgets.QDoubleSpinBox(self.gB_trajectory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_ang_incr.sizePolicy().hasHeightForWidth())
        self.sB_ang_incr.setSizePolicy(sizePolicy)
        self.sB_ang_incr.setMaximum(360.0)
        self.sB_ang_incr.setObjectName("sB_ang_incr")
        self.fLayout_traj_l.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sB_ang_incr)
        self.label_num_sweeps = QtWidgets.QLabel(self.gB_trajectory)
        self.label_num_sweeps.setEnabled(True)
        self.label_num_sweeps.setObjectName("label_num_sweeps")
        self.fLayout_traj_l.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_num_sweeps)
        self.sB_num_sweeps = QtWidgets.QSpinBox(self.gB_trajectory)
        self.sB_num_sweeps.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_num_sweeps.sizePolicy().hasHeightForWidth())
        self.sB_num_sweeps.setSizePolicy(sizePolicy)
        self.sB_num_sweeps.setMaximum(100)
        self.sB_num_sweeps.setProperty("value", 1)
        self.sB_num_sweeps.setObjectName("sB_num_sweeps")
        self.fLayout_traj_l.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sB_num_sweeps)
        self.horizontalLayout_2.addLayout(self.fLayout_traj_l)
        self.fLayout_traj_r = QtWidgets.QFormLayout()
        self.fLayout_traj_r.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.fLayout_traj_r.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fLayout_traj_r.setObjectName("fLayout_traj_r")
        self.label_num_proj = QtWidgets.QLabel(self.gB_trajectory)
        self.label_num_proj.setObjectName("label_num_proj")
        self.fLayout_traj_r.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_num_proj)
        self.sB_num_proj = QtWidgets.QSpinBox(self.gB_trajectory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_num_proj.sizePolicy().hasHeightForWidth())
        self.sB_num_proj.setSizePolicy(sizePolicy)
        self.sB_num_proj.setMaximum(3600)
        self.sB_num_proj.setObjectName("sB_num_proj")
        self.fLayout_traj_r.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sB_num_proj)
        self.label_det_off_u = QtWidgets.QLabel(self.gB_trajectory)
        self.label_det_off_u.setObjectName("label_det_off_u")
        self.fLayout_traj_r.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_det_off_u)
        self.sB_det_off_u = QtWidgets.QDoubleSpinBox(self.gB_trajectory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_det_off_u.sizePolicy().hasHeightForWidth())
        self.sB_det_off_u.setSizePolicy(sizePolicy)
        self.sB_det_off_u.setMaximum(2048.0)
        self.sB_det_off_u.setObjectName("sB_det_off_u")
        self.fLayout_traj_r.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sB_det_off_u)
        self.label_det_off_v = QtWidgets.QLabel(self.gB_trajectory)
        self.label_det_off_v.setObjectName("label_det_off_v")
        self.fLayout_traj_r.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_det_off_v)
        self.sB_det_off_v = QtWidgets.QDoubleSpinBox(self.gB_trajectory)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_det_off_v.sizePolicy().hasHeightForWidth())
        self.sB_det_off_v.setSizePolicy(sizePolicy)
        self.sB_det_off_v.setMaximum(2048.0)
        self.sB_det_off_v.setObjectName("sB_det_off_v")
        self.fLayout_traj_r.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sB_det_off_v)
        self.label_rot_ax = QtWidgets.QLabel(self.gB_trajectory)
        self.label_rot_ax.setEnabled(True)
        self.label_rot_ax.setObjectName("label_rot_ax")
        self.fLayout_traj_r.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_rot_ax)
        self.edi_rot_ax = QtWidgets.QLineEdit(self.gB_trajectory)
        self.edi_rot_ax.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edi_rot_ax.sizePolicy().hasHeightForWidth())
        self.edi_rot_ax.setSizePolicy(sizePolicy)
        self.edi_rot_ax.setObjectName("edi_rot_ax")
        self.fLayout_traj_r.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edi_rot_ax)
        self.horizontalLayout_2.addLayout(self.fLayout_traj_r)
        self.horizontalLayout.addWidget(self.gB_trajectory)
        self.gB_detector = QtWidgets.QGroupBox(self.config_tab_advanced)
        self.gB_detector.setObjectName("gB_detector")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gB_detector)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_det_width = QtWidgets.QLabel(self.gB_detector)
        self.label_det_width.setObjectName("label_det_width")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_det_width)
        self.sB_det_width = QtWidgets.QSpinBox(self.gB_detector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_det_width.sizePolicy().hasHeightForWidth())
        self.sB_det_width.setSizePolicy(sizePolicy)
        self.sB_det_width.setMaximum(8192)
        self.sB_det_width.setObjectName("sB_det_width")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sB_det_width)
        self.label_det_height = QtWidgets.QLabel(self.gB_detector)
        self.label_det_height.setObjectName("label_det_height")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_det_height)
        self.sB_det_height = QtWidgets.QSpinBox(self.gB_detector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_det_height.sizePolicy().hasHeightForWidth())
        self.sB_det_height.setSizePolicy(sizePolicy)
        self.sB_det_height.setPrefix("")
        self.sB_det_height.setMaximum(8192)
        self.sB_det_height.setObjectName("sB_det_height")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_det_height)
        self.label_pix_dim_x = QtWidgets.QLabel(self.gB_detector)
        self.label_pix_dim_x.setObjectName("label_pix_dim_x")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_pix_dim_x)
        self.sB_pix_dim_x = QtWidgets.QDoubleSpinBox(self.gB_detector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_pix_dim_x.sizePolicy().hasHeightForWidth())
        self.sB_pix_dim_x.setSizePolicy(sizePolicy)
        self.sB_pix_dim_x.setMinimum(0.01)
        self.sB_pix_dim_x.setMaximum(10.0)
        self.sB_pix_dim_x.setProperty("value", 1.0)
        self.sB_pix_dim_x.setObjectName("sB_pix_dim_x")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sB_pix_dim_x)
        self.label_pix_dim_y = QtWidgets.QLabel(self.gB_detector)
        self.label_pix_dim_y.setObjectName("label_pix_dim_y")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_pix_dim_y)
        self.sB_pix_dim_y = QtWidgets.QDoubleSpinBox(self.gB_detector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_pix_dim_y.sizePolicy().hasHeightForWidth())
        self.sB_pix_dim_y.setSizePolicy(sizePolicy)
        self.sB_pix_dim_y.setDecimals(2)
        self.sB_pix_dim_y.setMinimum(0.01)
        self.sB_pix_dim_y.setMaximum(10.0)
        self.sB_pix_dim_y.setProperty("value", 1.0)
        self.sB_pix_dim_y.setObjectName("sB_pix_dim_y")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sB_pix_dim_y)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout.addWidget(self.gB_detector)
        self.gB_volume = QtWidgets.QGroupBox(self.config_tab_advanced)
        self.gB_volume.setObjectName("gB_volume")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gB_volume)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.vLayout_reco_dim = QtWidgets.QVBoxLayout()
        self.vLayout_reco_dim.setObjectName("vLayout_reco_dim")
        self.fLayout_volume_size = QtWidgets.QFormLayout()
        self.fLayout_volume_size.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.fLayout_volume_size.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fLayout_volume_size.setObjectName("fLayout_volume_size")
        self.label_reco_dim_x = QtWidgets.QLabel(self.gB_volume)
        self.label_reco_dim_x.setObjectName("label_reco_dim_x")
        self.fLayout_volume_size.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_reco_dim_x)
        self.sB_reco_dim_x = QtWidgets.QSpinBox(self.gB_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_reco_dim_x.sizePolicy().hasHeightForWidth())
        self.sB_reco_dim_x.setSizePolicy(sizePolicy)
        self.sB_reco_dim_x.setMaximum(4096)
        self.sB_reco_dim_x.setObjectName("sB_reco_dim_x")
        self.fLayout_volume_size.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sB_reco_dim_x)
        self.label_reco_dim_y = QtWidgets.QLabel(self.gB_volume)
        self.label_reco_dim_y.setObjectName("label_reco_dim_y")
        self.fLayout_volume_size.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_reco_dim_y)
        self.sB_reco_dim_y = QtWidgets.QSpinBox(self.gB_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_reco_dim_y.sizePolicy().hasHeightForWidth())
        self.sB_reco_dim_y.setSizePolicy(sizePolicy)
        self.sB_reco_dim_y.setMaximum(4096)
        self.sB_reco_dim_y.setObjectName("sB_reco_dim_y")
        self.fLayout_volume_size.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_reco_dim_y)
        self.label_reco_dim_z = QtWidgets.QLabel(self.gB_volume)
        self.label_reco_dim_z.setObjectName("label_reco_dim_z")
        self.fLayout_volume_size.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_reco_dim_z)
        self.sB_reco_dim_z = QtWidgets.QSpinBox(self.gB_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_reco_dim_z.sizePolicy().hasHeightForWidth())
        self.sB_reco_dim_z.setSizePolicy(sizePolicy)
        self.sB_reco_dim_z.setMaximum(4096)
        self.sB_reco_dim_z.setObjectName("sB_reco_dim_z")
        self.fLayout_volume_size.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sB_reco_dim_z)
        self.vLayout_reco_dim.addLayout(self.fLayout_volume_size)
        self.pB_set_reco_dim = QtWidgets.QPushButton(self.gB_volume)
        self.pB_set_reco_dim.setObjectName("pB_set_reco_dim")
        self.vLayout_reco_dim.addWidget(self.pB_set_reco_dim)
        self.horizontalLayout_4.addLayout(self.vLayout_reco_dim)
        self.fLayout_volume_spacing = QtWidgets.QFormLayout()
        self.fLayout_volume_spacing.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.fLayout_volume_spacing.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fLayout_volume_spacing.setObjectName("fLayout_volume_spacing")
        self.label_reco_spacing_x = QtWidgets.QLabel(self.gB_volume)
        self.label_reco_spacing_x.setObjectName("label_reco_spacing_x")
        self.fLayout_volume_spacing.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_reco_spacing_x)
        self.sB_reco_spacing_x = QtWidgets.QDoubleSpinBox(self.gB_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_reco_spacing_x.sizePolicy().hasHeightForWidth())
        self.sB_reco_spacing_x.setSizePolicy(sizePolicy)
        self.sB_reco_spacing_x.setMaximum(10.0)
        self.sB_reco_spacing_x.setObjectName("sB_reco_spacing_x")
        self.fLayout_volume_spacing.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sB_reco_spacing_x)
        self.label_reco_spacing_y = QtWidgets.QLabel(self.gB_volume)
        self.label_reco_spacing_y.setObjectName("label_reco_spacing_y")
        self.fLayout_volume_spacing.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_reco_spacing_y)
        self.sB_reco_spacing_y = QtWidgets.QDoubleSpinBox(self.gB_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_reco_spacing_y.sizePolicy().hasHeightForWidth())
        self.sB_reco_spacing_y.setSizePolicy(sizePolicy)
        self.sB_reco_spacing_y.setMaximum(10.0)
        self.sB_reco_spacing_y.setObjectName("sB_reco_spacing_y")
        self.fLayout_volume_spacing.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sB_reco_spacing_y)
        self.label_reco_spacing_z = QtWidgets.QLabel(self.gB_volume)
        self.label_reco_spacing_z.setObjectName("label_reco_spacing_z")
        self.fLayout_volume_spacing.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_reco_spacing_z)
        self.sB_reco_spacing_z = QtWidgets.QDoubleSpinBox(self.gB_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_reco_spacing_z.sizePolicy().hasHeightForWidth())
        self.sB_reco_spacing_z.setSizePolicy(sizePolicy)
        self.sB_reco_spacing_z.setMaximum(10.0)
        self.sB_reco_spacing_z.setObjectName("sB_reco_spacing_z")
        self.fLayout_volume_spacing.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sB_reco_spacing_z)
        self.horizontalLayout_4.addLayout(self.fLayout_volume_spacing)
        self.horizontalLayout.addWidget(self.gB_volume)
        self.gB_filter = QtWidgets.QGroupBox(self.config_tab_advanced)
        self.gB_filter.setObjectName("gB_filter")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gB_filter)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cB_cosine_filter = QtWidgets.QCheckBox(self.gB_filter)
        self.cB_cosine_filter.setChecked(False)
        self.cB_cosine_filter.setObjectName("cB_cosine_filter")
        self.verticalLayout_3.addWidget(self.cB_cosine_filter)
        self.cB_ramlak_filter = QtWidgets.QCheckBox(self.gB_filter)
        self.cB_ramlak_filter.setChecked(False)
        self.cB_ramlak_filter.setObjectName("cB_ramlak_filter")
        self.verticalLayout_3.addWidget(self.cB_ramlak_filter)
        self.horizontalLayout.addWidget(self.gB_filter)
        self.gB_reco = QtWidgets.QGroupBox(self.config_tab_advanced)
        self.gB_reco.setObjectName("gB_reco")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gB_reco)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rB_all = QtWidgets.QRadioButton(self.gB_reco)
        self.rB_all.setChecked(True)
        self.rB_all.setObjectName("rB_all")
        self.verticalLayout_2.addWidget(self.rB_all)
        self.rB_stepwise = QtWidgets.QRadioButton(self.gB_reco)
        self.rB_stepwise.setChecked(False)
        self.rB_stepwise.setObjectName("rB_stepwise")
        self.verticalLayout_2.addWidget(self.rB_stepwise)
        self.horizontalLayout.addWidget(self.gB_reco)
        self.vLayout_config_btns = QtWidgets.QVBoxLayout()
        self.vLayout_config_btns.setObjectName("vLayout_config_btns")
        self.pB_reset_config = QtWidgets.QPushButton(self.config_tab_advanced)
        self.pB_reset_config.setObjectName("pB_reset_config")
        self.vLayout_config_btns.addWidget(self.pB_reset_config)
        self.cB_use_cl = QtWidgets.QCheckBox(self.config_tab_advanced)
        self.cB_use_cl.setChecked(True)
        self.cB_use_cl.setObjectName("cB_use_cl")
        self.vLayout_config_btns.addWidget(self.cB_use_cl)
        self.horizontalLayout.addLayout(self.vLayout_config_btns)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.config_tabs.addTab(self.config_tab_advanced, "")
        self.verticalLayout.addWidget(self.config_tabs)
        self.hLayout_reco = QtWidgets.QHBoxLayout()
        self.hLayout_reco.setObjectName("hLayout_reco")
        self.frame_3D = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3D.sizePolicy().hasHeightForWidth())
        self.frame_3D.setSizePolicy(sizePolicy)
        self.frame_3D.setObjectName("frame_3D")
        self.vLayout_3D = QtWidgets.QVBoxLayout(self.frame_3D)
        self.vLayout_3D.setContentsMargins(0, 0, 0, 0)
        self.vLayout_3D.setObjectName("vLayout_3D")
        self.view_3D = QtWidgets.QFrame(self.frame_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_3D.sizePolicy().hasHeightForWidth())
        self.view_3D.setSizePolicy(sizePolicy)
        self.view_3D.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_3D.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_3D.setObjectName("view_3D")
        self.vLayout_3D.addWidget(self.view_3D)
        self.hLayout_3D_btm = QtWidgets.QHBoxLayout()
        self.hLayout_3D_btm.setObjectName("hLayout_3D_btm")
        self.label_angles = QtWidgets.QLabel(self.frame_3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_angles.sizePolicy().hasHeightForWidth())
        self.label_angles.setSizePolicy(sizePolicy)
        self.label_angles.setStyleSheet("")
        self.label_angles.setObjectName("label_angles")
        self.hLayout_3D_btm.addWidget(self.label_angles)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_3D_btm.addItem(spacerItem2)
        self.pB_demo = QtWidgets.QPushButton(self.frame_3D)
        self.pB_demo.setObjectName("pB_demo")
        self.hLayout_3D_btm.addWidget(self.pB_demo)
        self.pB_reset_view = QtWidgets.QPushButton(self.frame_3D)
        self.pB_reset_view.setObjectName("pB_reset_view")
        self.hLayout_3D_btm.addWidget(self.pB_reset_view)
        self.vLayout_3D.addLayout(self.hLayout_3D_btm)
        self.hLayout_reco.addWidget(self.frame_3D)
        self.frame_fwd_proj_btns = QtWidgets.QFrame(self.centralwidget)
        self.frame_fwd_proj_btns.setObjectName("frame_fwd_proj_btns")
        self.vLayout_scan_btn = QtWidgets.QVBoxLayout(self.frame_fwd_proj_btns)
        self.vLayout_scan_btn.setContentsMargins(0, 0, 0, 0)
        self.vLayout_scan_btn.setObjectName("vLayout_scan_btn")
        self.pB_fwd_proj = QtWidgets.QPushButton(self.frame_fwd_proj_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_fwd_proj.sizePolicy().hasHeightForWidth())
        self.pB_fwd_proj.setSizePolicy(sizePolicy)
        self.pB_fwd_proj.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pB_fwd_proj.setObjectName("pB_fwd_proj")
        self.vLayout_scan_btn.addWidget(self.pB_fwd_proj)
        self.pB_fluoro = QtWidgets.QPushButton(self.frame_fwd_proj_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_fluoro.sizePolicy().hasHeightForWidth())
        self.pB_fluoro.setSizePolicy(sizePolicy)
        self.pB_fluoro.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pB_fluoro.setObjectName("pB_fluoro")
        self.vLayout_scan_btn.addWidget(self.pB_fluoro)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vLayout_scan_btn.addItem(spacerItem3)
        self.hLayout_reco.addWidget(self.frame_fwd_proj_btns)
        self.frame_fwd_proj = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_fwd_proj.sizePolicy().hasHeightForWidth())
        self.frame_fwd_proj.setSizePolicy(sizePolicy)
        self.frame_fwd_proj.setObjectName("frame_fwd_proj")
        self.vLayout_fwd_proj = QtWidgets.QVBoxLayout(self.frame_fwd_proj)
        self.vLayout_fwd_proj.setContentsMargins(0, 0, 0, 0)
        self.vLayout_fwd_proj.setObjectName("vLayout_fwd_proj")
        self.gV_fwd_proj = GraphicsView(self.frame_fwd_proj)
        self.gV_fwd_proj.setStyleSheet("background: black;\n"
"border: none")
        self.gV_fwd_proj.setObjectName("gV_fwd_proj")
        self.vLayout_fwd_proj.addWidget(self.gV_fwd_proj)
        self.hLayout_fwd_proj_btm = QtWidgets.QHBoxLayout()
        self.hLayout_fwd_proj_btm.setContentsMargins(-1, 8, -1, 8)
        self.hLayout_fwd_proj_btm.setObjectName("hLayout_fwd_proj_btm")
        self.pB_fwd_proj_play_pause = QtWidgets.QPushButton(self.frame_fwd_proj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_fwd_proj_play_pause.sizePolicy().hasHeightForWidth())
        self.pB_fwd_proj_play_pause.setSizePolicy(sizePolicy)
        self.pB_fwd_proj_play_pause.setStyleSheet("QPushButton{border:0}")
        self.pB_fwd_proj_play_pause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_fwd_proj_play_pause.setIcon(icon)
        self.pB_fwd_proj_play_pause.setFlat(True)
        self.pB_fwd_proj_play_pause.setObjectName("pB_fwd_proj_play_pause")
        self.hLayout_fwd_proj_btm.addWidget(self.pB_fwd_proj_play_pause)
        self.scroll_fwd_proj = QtWidgets.QScrollBar(self.frame_fwd_proj)
        self.scroll_fwd_proj.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_fwd_proj.setInvertedAppearance(False)
        self.scroll_fwd_proj.setInvertedControls(True)
        self.scroll_fwd_proj.setObjectName("scroll_fwd_proj")
        self.hLayout_fwd_proj_btm.addWidget(self.scroll_fwd_proj)
        self.vLayout_fwd_proj.addLayout(self.hLayout_fwd_proj_btm)
        self.hLayout_reco.addWidget(self.frame_fwd_proj)
        self.frame_back_proj_btns = QtWidgets.QFrame(self.centralwidget)
        self.frame_back_proj_btns.setObjectName("frame_back_proj_btns")
        self.vLayout_reco_btn = QtWidgets.QVBoxLayout(self.frame_back_proj_btns)
        self.vLayout_reco_btn.setContentsMargins(0, 0, 0, 0)
        self.vLayout_reco_btn.setObjectName("vLayout_reco_btn")
        self.pB_back_proj = QtWidgets.QPushButton(self.frame_back_proj_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_back_proj.sizePolicy().hasHeightForWidth())
        self.pB_back_proj.setSizePolicy(sizePolicy)
        self.pB_back_proj.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pB_back_proj.setObjectName("pB_back_proj")
        self.vLayout_reco_btn.addWidget(self.pB_back_proj)
        self.sB_speed = QtWidgets.QSpinBox(self.frame_back_proj_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sB_speed.sizePolicy().hasHeightForWidth())
        self.sB_speed.setSizePolicy(sizePolicy)
        self.sB_speed.setMinimumSize(QtCore.QSize(0, 23))
        self.sB_speed.setMinimum(1)
        self.sB_speed.setMaximum(6)
        self.sB_speed.setProperty("value", 3)
        self.sB_speed.setObjectName("sB_speed")
        self.vLayout_reco_btn.addWidget(self.sB_speed)
        self.hLayout_reco.addWidget(self.frame_back_proj_btns)
        self.frame_back_proj = QtWidgets.QFrame(self.centralwidget)
        self.frame_back_proj.setObjectName("frame_back_proj")
        self.vLayout_back_proj = QtWidgets.QVBoxLayout(self.frame_back_proj)
        self.vLayout_back_proj.setContentsMargins(0, 0, 0, 0)
        self.vLayout_back_proj.setObjectName("vLayout_back_proj")
        self.gV_back_proj = GraphicsView(self.frame_back_proj)
        self.gV_back_proj.setStyleSheet("background: black;\n"
"border: none")
        self.gV_back_proj.setObjectName("gV_back_proj")
        self.vLayout_back_proj.addWidget(self.gV_back_proj)
        self.hLayout_back_proj_btm = QtWidgets.QHBoxLayout()
        self.hLayout_back_proj_btm.setObjectName("hLayout_back_proj_btm")
        self.pB_back_proj_play_pause = QtWidgets.QPushButton(self.frame_back_proj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_back_proj_play_pause.sizePolicy().hasHeightForWidth())
        self.pB_back_proj_play_pause.setSizePolicy(sizePolicy)
        self.pB_back_proj_play_pause.setStyleSheet("QPushButton{border:0}")
        self.pB_back_proj_play_pause.setText("")
        self.pB_back_proj_play_pause.setIcon(icon)
        self.pB_back_proj_play_pause.setFlat(True)
        self.pB_back_proj_play_pause.setObjectName("pB_back_proj_play_pause")
        self.hLayout_back_proj_btm.addWidget(self.pB_back_proj_play_pause)
        self.scroll_back_proj = QtWidgets.QScrollBar(self.frame_back_proj)
        self.scroll_back_proj.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_back_proj.setObjectName("scroll_back_proj")
        self.hLayout_back_proj_btm.addWidget(self.scroll_back_proj)
        self.comboBox_plane_sel = QtWidgets.QComboBox(self.frame_back_proj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_plane_sel.sizePolicy().hasHeightForWidth())
        self.comboBox_plane_sel.setSizePolicy(sizePolicy)
        self.comboBox_plane_sel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_plane_sel.setObjectName("comboBox_plane_sel")
        self.comboBox_plane_sel.addItem("")
        self.comboBox_plane_sel.addItem("")
        self.comboBox_plane_sel.addItem("")
        self.hLayout_back_proj_btm.addWidget(self.comboBox_plane_sel)
        self.vLayout_back_proj.addLayout(self.hLayout_back_proj_btm)
        self.hLayout_reco.addWidget(self.frame_back_proj)
        self.verticalLayout.addLayout(self.hLayout_reco)
        Interactive_Cone_Beam_Reconstruction.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Interactive_Cone_Beam_Reconstruction)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2263, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLanguage = QtWidgets.QMenu(self.menubar)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        Interactive_Cone_Beam_Reconstruction.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(Interactive_Cone_Beam_Reconstruction)
        self.statusBar.setObjectName("statusBar")
        Interactive_Cone_Beam_Reconstruction.setStatusBar(self.statusBar)
        self.action_open_3D_data = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        icon = QtGui.QIcon.fromTheme(":/icons/open")
        self.action_open_3D_data.setIcon(icon)
        self.action_open_3D_data.setObjectName("action_open_3D_data")
        self.action_change_lang_en_GB = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_change_lang_en_GB.setObjectName("action_change_lang_en_GB")
        self.action_change_lang_de_DE = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_change_lang_de_DE.setObjectName("action_change_lang_de_DE")
        self.action_load_config = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        icon = QtGui.QIcon.fromTheme(":/icons/open")
        self.action_load_config.setIcon(icon)
        self.action_load_config.setObjectName("action_load_config")
        self.action_save_config = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        icon = QtGui.QIcon.fromTheme(":/icons/save")
        self.action_save_config.setIcon(icon)
        self.action_save_config.setObjectName("action_save_config")
        self.action_voxelize = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        icon = QtGui.QIcon.fromTheme(":/icons/voxelize")
        self.action_voxelize.setIcon(icon)
        self.action_voxelize.setObjectName("action_voxelize")
        self.action_set_phantom = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_set_phantom.setObjectName("action_set_phantom")
        self.action_show_3D = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_show_3D.setCheckable(True)
        self.action_show_3D.setChecked(True)
        self.action_show_3D.setObjectName("action_show_3D")
        self.action_show_fwd_proj = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_show_fwd_proj.setCheckable(True)
        self.action_show_fwd_proj.setChecked(True)
        self.action_show_fwd_proj.setObjectName("action_show_fwd_proj")
        self.action_show_back_proj = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_show_back_proj.setCheckable(True)
        self.action_show_back_proj.setChecked(True)
        self.action_show_back_proj.setObjectName("action_show_back_proj")
        self.action_show_config = QtWidgets.QAction(Interactive_Cone_Beam_Reconstruction)
        self.action_show_config.setCheckable(True)
        self.action_show_config.setChecked(True)
        self.action_show_config.setObjectName("action_show_config")
        self.menuFile.addAction(self.action_open_3D_data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_load_config)
        self.menuFile.addAction(self.action_save_config)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_voxelize)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_set_phantom)
        self.menuView.addAction(self.action_show_3D)
        self.menuView.addAction(self.action_show_fwd_proj)
        self.menuView.addAction(self.action_show_back_proj)
        self.menuView.addAction(self.action_show_config)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuLanguage.menuAction())

        self.retranslateUi(Interactive_Cone_Beam_Reconstruction)
        self.config_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Interactive_Cone_Beam_Reconstruction)

    def retranslateUi(self, Interactive_Cone_Beam_Reconstruction):
        _translate = QtCore.QCoreApplication.translate
        Interactive_Cone_Beam_Reconstruction.setWindowTitle(_translate("Interactive_Cone_Beam_Reconstruction", "Interactive Cone Beam Reconstruction"))
        self.label_sdd_simple.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Source to detector distance"))
        self.label_sid_simple.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Source to patient distance"))
        self.sB_sdd_simple.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.sB_sid_simple.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.label_det_width_simple.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Detector size x"))
        self.sB_det_width_simple.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " px"))
        self.label_det_height_simple.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Detector size y"))
        self.sB_det_height_simple.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " px"))
        self.config_tabs.setTabText(self.config_tabs.indexOf(self.config_tab_simple), _translate("Interactive_Cone_Beam_Reconstruction", "Simple"))
        self.gB_trajectory.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "Trajectory"))
        self.label_sdd.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Source to detector distance"))
        self.sB_sdd.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.label_sid.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Source to patient distance"))
        self.sB_sid.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.label_ang_incr.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Average angular increment"))
        self.sB_ang_incr.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", "°"))
        self.label_num_sweeps.setText(_translate("Interactive_Cone_Beam_Reconstruction", "No. of sweeps"))
        self.label_num_proj.setText(_translate("Interactive_Cone_Beam_Reconstruction", "No. of projections"))
        self.label_det_off_u.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Detector offset u"))
        self.sB_det_off_u.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " px"))
        self.label_det_off_v.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Detector offset v"))
        self.sB_det_off_v.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " px"))
        self.label_rot_ax.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Rotation axis"))
        self.edi_rot_ax.setText(_translate("Interactive_Cone_Beam_Reconstruction", "[0.0; 0.0; 1.0]"))
        self.gB_detector.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "Detector"))
        self.label_det_width.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Detector size x"))
        self.sB_det_width.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " px"))
        self.label_det_height.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Detector size y"))
        self.sB_det_height.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " px"))
        self.label_pix_dim_x.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Pixel spacing x"))
        self.sB_pix_dim_x.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.label_pix_dim_y.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Pixel spacing y"))
        self.sB_pix_dim_y.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.gB_volume.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "Volume"))
        self.label_reco_dim_x.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Size x"))
        self.sB_reco_dim_x.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " voxel"))
        self.label_reco_dim_y.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Size y"))
        self.sB_reco_dim_y.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " voxel"))
        self.label_reco_dim_z.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Size z"))
        self.sB_reco_dim_z.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " voxel"))
        self.pB_set_reco_dim.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Set to phantom size"))
        self.label_reco_spacing_x.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Spacing x"))
        self.sB_reco_spacing_x.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.label_reco_spacing_y.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Spacing y"))
        self.sB_reco_spacing_y.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.label_reco_spacing_z.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Spacing z"))
        self.sB_reco_spacing_z.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", " mm"))
        self.gB_filter.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "Filters"))
        self.cB_cosine_filter.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Cosine"))
        self.cB_ramlak_filter.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Ramlak"))
        self.gB_reco.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "Show steps"))
        self.rB_all.setText(_translate("Interactive_Cone_Beam_Reconstruction", "all at once"))
        self.rB_stepwise.setText(_translate("Interactive_Cone_Beam_Reconstruction", "stepwise"))
        self.pB_reset_config.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Reset"))
        self.cB_use_cl.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Use GPU"))
        self.config_tabs.setTabText(self.config_tabs.indexOf(self.config_tab_advanced), _translate("Interactive_Cone_Beam_Reconstruction", "Advanced"))
        self.label_angles.setText(_translate("Interactive_Cone_Beam_Reconstruction", "LAO/RAO: 0°    CRAN/CAUD: 0°"))
        self.pB_demo.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Demo acquisition"))
        self.pB_reset_view.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Reset view"))
        self.pB_fwd_proj.setText(_translate("Interactive_Cone_Beam_Reconstruction", "S\n"
"C\n"
"A\n"
"N"))
        self.pB_fluoro.setText(_translate("Interactive_Cone_Beam_Reconstruction", "F\n"
"L\n"
"U\n"
"O\n"
"R\n"
"O"))
        self.pB_back_proj.setText(_translate("Interactive_Cone_Beam_Reconstruction", "R\n"
"E\n"
"C\n"
"O\n"
"N\n"
"S\n"
"T\n"
"R\n"
"U\n"
"C\n"
"T\n"
"I\n"
"O\n"
"N"))
        self.sB_speed.setToolTip(_translate("Interactive_Cone_Beam_Reconstruction", "playback speed"))
        self.sB_speed.setSuffix(_translate("Interactive_Cone_Beam_Reconstruction", "x"))
        self.comboBox_plane_sel.setItemText(0, _translate("Interactive_Cone_Beam_Reconstruction", "Axial"))
        self.comboBox_plane_sel.setItemText(1, _translate("Interactive_Cone_Beam_Reconstruction", "Sagittal"))
        self.comboBox_plane_sel.setItemText(2, _translate("Interactive_Cone_Beam_Reconstruction", "Coronal"))
        self.menuFile.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "File"))
        self.menuLanguage.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "&Language"))
        self.menuView.setTitle(_translate("Interactive_Cone_Beam_Reconstruction", "View"))
        self.action_open_3D_data.setText(_translate("Interactive_Cone_Beam_Reconstruction", "&Open 3D Data"))
        self.action_open_3D_data.setShortcut(_translate("Interactive_Cone_Beam_Reconstruction", "Ctrl+O"))
        self.action_change_lang_en_GB.setText(_translate("Interactive_Cone_Beam_Reconstruction", "&English"))
        self.action_change_lang_de_DE.setText(_translate("Interactive_Cone_Beam_Reconstruction", "&Deutsch"))
        self.action_load_config.setText(_translate("Interactive_Cone_Beam_Reconstruction", "&Load Configuration"))
        self.action_save_config.setText(_translate("Interactive_Cone_Beam_Reconstruction", "&Save Configuration as..."))
        self.action_voxelize.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Voxelize Mesh"))
        self.action_set_phantom.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Set Phantom array"))
        self.action_show_3D.setText(_translate("Interactive_Cone_Beam_Reconstruction", "3D"))
        self.action_show_fwd_proj.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Projection"))
        self.action_show_back_proj.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Backprojection"))
        self.action_show_config.setText(_translate("Interactive_Cone_Beam_Reconstruction", "Configuration"))

from GraphicsView import GraphicsView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interactive_Cone_Beam_Reconstruction = QtWidgets.QMainWindow()
    ui = Ui_Interactive_Cone_Beam_Reconstruction()
    ui.setupUi(Interactive_Cone_Beam_Reconstruction)
    Interactive_Cone_Beam_Reconstruction.show()
    sys.exit(app.exec_())

